:bug: link changed from li-job-description to /tldr
ash1eygrace/ai-content pull request #53
Opened 2023-03-31 13:29 UTC by Mr-G-D

The link for tl;dr is changed from black page to tl;dr generator page

2023-03-31 22:59 UTC, ash1eygrace requested changes

2023-03-31 22:59 UTC, ash1eygrace commented on src/data/GeneratorList.js
> +    link: "/tldr",
Thanks again for working on this! 

For the sake of consistency throughout the data, let's remove the `/` (forward slash) as the other generators don't have one.

2023-04-01 02:03 UTC, Mr-G-D commented
@ash1eygrace 
Changes made

2023-04-01 12:29 UTC, ash1eygrace approved these changes
Thanks again for working on this!

2023-04-01 12:29 UTC, merged